esphome:
  name: temperature-sensor-prototype
  friendly_name: temperature_sensor_prototype

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MNhm8VZBTUy8VBMYYILBMo1P0jRoY2jAZf90Usr1PDY="

ota:
  - platform: esphome
    password: "a180e6a84859b1a20fbbe33858201832"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature-Sensor-Prototype"
    password: "lQlRcPCcliro"

captive_portal:
    
sensor:
  - platform: dht
    pin: GPIO22
    temperature:
      name: "DHT11 Temperature"
    humidity:
      name: "DHT11 Humidity"
    update_interval: 5s